export const currentKings = [
  {
    title: "King of Europe",
    team: "Paris Saint-Germain",
    teamLogo: "https://media.api-sports.io/football/teams/85.png",
    detail: "Champions League Winner",
    year: 2026,
  },
  {
    title: "King of the clubs",
    team: "Chelsea",
    teamLogo: "https://media.api-sports.io/football/teams/49.png",
    detail: "Club World Cup Winner",
    year: 2025,
  },
  {
    title: "King of Spain",
    team: "Barcelona",
    teamLogo: "https://media.api-sports.io/football/teams/529.png",
    detail: "La Liga Winner",
    year: 2026,
  },
  {
    title: "King of England",
    team: "Liverpool",
    teamLogo: "https://media.api-sports.io/football/teams/40.png",
    detail: "Premier League Winner",
    year: 2026,
  },
  {
    title: "King of Italy",
    team: "Napoli",
    teamLogo: "https://media.api-sports.io/football/teams/492.png",
    detail: "Serie A Winner",
    year: 2026,
  },
  {
    title: "King of Germany",
    team: "Bayern Munich",
    teamLogo: "https://media.api-sports.io/football/teams/157.png",
    detail: "Bundesliga Winner",
    year: 2026,
  },
  {
    title: "King of France",
    team: "Paris Saint-Germain",
    teamLogo: "https://media.api-sports.io/football/teams/85.png",
    detail: "Ligue 1 Winner",
    year: 2026,
  },
  {
    title: "King of the world",
    team: "Spain",
    teamLogo: "https://media.api-sports.io/football/teams/9.png",
    detail: "World cup Winner",
    year: 2026,
  },
];

export const historicalKings = [
  {
    title: "All-Time King of Europe",
    team: "Real Madrid",
    teamLogo: "https://media.api-sports.io/football/teams/541.png",
    detail: "Most Champions League Titles",
    year: 15,
  },
  {
    title: "All-Time King of the clubs",
    team: "Real Madrid",
    teamLogo: "https://media.api-sports.io/football/teams/541.png",
    detail: "Most Club World Cup Titles",
    year: 6,
  },
  {
    title: "All-Time King of Spain",
    team: "Real Madrid",
    teamLogo: "https://media.api-sports.io/football/teams/541.png",
    detail: "Most La Liga Titles",
    year: 36,
  },
  {
    title: "All-Time King of England",
    team: "Manchester United",
    teamLogo: "https://media.api-sports.io/football/teams/33.png",
    detail: "Most Premier League Titles",
    year: 13,
  },
  {
    title: "All-Time King of Italy",
    team: "Juventus",
    teamLogo: "https://media.api-sports.io/football/teams/496.png",
    detail: "Most Serie A Titles",
    year: 36,
  },
  {
    title: "All-Time King of Germany",
    team: "Bayern Munich",
    teamLogo: "https://media.api-sports.io/football/teams/157.png",
    detail: "Most Bundesliga Titles",
    year: 34,
  },
  {
    title: "All-Time King of France",
    team: "Paris Saint-Germain",
    teamLogo: "https://media.api-sports.io/football/teams/85.png",
    detail: "Most Ligue 1 Titles",
    year: 13,
  },
  {
    title: "All-Time King of the world",
    team: "Brazil",
    teamLogo: "https://media.api-sports.io/football/teams/6.png",
    detail: "Most World cup titles",
    year: 5,
  },
];